name: gh_page

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
    branches: [master]
#   pull_request:
#     branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout flant
        uses: actions/checkout@v2
        with:
          repository: Binbiubiubiu/flant
          ref: master
      - name: Checkout flant_app
        uses: actions/checkout@v2
        with:
          path: example
          ref: master
      - name: Flutter action
        # You may pin to the exact commit or the version.
        # uses: subosito/flutter-action@26bf50084a0c218b5b715a3641c36eac84fd2136
        uses: subosito/flutter-action@v2.4.0
        with:
          flutter-version: 3.0.4
          cache: true
          cache-key: key-20220712
          cache-path: ${{ runner.tool_cache }}/flutter/3.0.4-stable

      # 下载项目依赖
      - name: Install dependencies
        run: flutter pub get

      # 执行测试
      # - run: flutter test
      # 打包 Web
      - run: flutter build web --release -t lib/main.dart --web-renderer=html --pwa-strategy=none
        working-directory: example
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build/web
