# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout flant
        uses: actions/checkout@v2
        with:
          repository: Simon-Bin/flant
          ref: master
      - name: Checkout flant_app
        uses: actions/checkout@v2
        with:
          path: example
          ref: master
      - name: set up JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: Flutter action
        # You may pin to the exact commit or the version.
        # uses: subosito/flutter-action@26bf50084a0c218b5b715a3641c36eac84fd2136
        uses: subosito/flutter-action@v1.4.0
        with:
          # The Flutter version to make available on the path
          flutter-version: "2.x" # optional
          # The Flutter build release channel
          channel: "stable" # optional, default is stable

      # 下载项目依赖
      - name: Install dependencies
        run: flutter pub get

      # 执行测试
      # - run: flutter test
      # 打包 APK
      - run: cd example && flutter build apk --release -t lib/main.dart --split-per-abi --obfuscate --split-debug-info=./
      # https://github.com/svenstaro/upload-release-action
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          # A personal access token for the GitHub repository in which the release will be created and edited.
          # It is recommended to create the access token with the following scopes: `repo, user, admin:repo_hook`.
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: example/build/app/outputs/flutter-apk/*.apk
          file_glob: true
          tag: ${{ github.ref }}
#       - name: Upload Release
#         uses: actions/upload-artifact@v2
#         with:
#           name: relase-apk
#           path: example/build/app/outputs/apk/release/*.apk

